#!/bin/bash

# Bash Script to download and install the required programs for Eval, move the output files to 
# Home directory, then remove programs

# Prowler install and run
git clone https://github.com/prowler-cloud/prowler
cd prowler
./prowler -M csv -f us-east-1,us-west-2

# goes to output folder and moves the file to cloudshell-user home for ease of download
cd /home/cloudshell-user/AWS/prowler/output
mv *.csv /home/cloudshell-user/

# Cloudsplaining install and run
pip3 install --user cloudsplaining
cloudsplaining download
cloudsplaining create-exclusions-file
cloudsplaining scan --exclusions-file exclusions.yml --input-file default.json

# getting the account ID
aws sts get-caller-identity

cd /home/cloudshell-user
ls

# removing the things
rm -r AWS
pip3 uninstall cloudsplaining
rm default.json
rm exclusions.yml
